version: '3'
services:

  auth_db:
    container_name: auth_db
    image: postgres:16.2
    restart: always
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=admin
      - POSTGRES_DB=auth_db
    ports:
      - "5434:5432"

volumes:
  auth_db_data:
